services:
  go-server:
    build:
      context: .
      dockerfile: go_server/Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./model:/app/model:ro

  py-server:
    build:
      context: .
      dockerfile: py_server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model:ro
