services:
  go-server:
    build:
      context: .
      dockerfile: go_server/Dockerfile
    volumes:
      - ./model:/app/model:ro

  py-server:
    build:
      context: .
      dockerfile: py_server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model:ro

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - go-server