scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cAdvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cAdvisor:8080"]
